version: '3'
services:
  haproxy:
    image: haproxy:lts
    container_name: haproxy
    restart: unless-stopped
    environment:
      TZ: "Asia/Kolkata"
    volumes:
      - /opt/haproxy:/usr/local/etc/haproxy
      - /usr/local/etc/haproxy/ssl/:/usr/local/etc/haproxy/ssl/
    ports:
      - 80:80
      - 443:443
      - 8001:8001